Random_list, sum & average
alinadmytriv/labs pull request #2
Opened 2019-09-27 20:22 UTC by alinadmytriv

Create a random list of X elements, iterate through list of randoms and calculate its sum and average.

2019-10-07 14:50 UTC, polyakovartem requested changes

2019-10-07 14:50 UTC, polyakovartem commented on laboratorna1/random_list.py
> +print(random_list)
same comment as for lab2

2019-10-07 14:50 UTC, polyakovartem commented on laboratorna1/random_list.py
> +z = int(input("Enter number for the ending: "))
please, create the separate function for this

2019-10-08 15:00 UTC, polyakovartem requested changes
please do not create a new file, make all the modification in an old one

2019-10-08 15:00 UTC, polyakovartem commented on lab1/random_list0.py
> +    z = int(input("Enter number for the ending: "))
move input into separate function

2019-10-08 15:00 UTC, polyakovartem commented on lab1/random_list0.py
> +    print("Average - " + str(average(l)))
move result printing into separate function

2019-10-08 15:00 UTC, polyakovartem commented on lab1/random_list0.py
> +def create_list(x0, y0, z0):
please use informative parameter names

2019-10-08 15:26 UTC, polyakovartem requested changes
why did you create a new file one more time?

2019-10-08 15:40 UTC, alinadmytriv commented
I am just training to understad how to use the github yet. I thought I need to send a new file. I need to send you the code in the Resolve conversation?

2019-10-09 06:50 UTC, polyakovartem commented
to understand, please read https://www.atlassian.com/git/tutorials/what-is-version-control
and https://www.atlassian.com/git/tutorials/making-a-pull-request

2019-10-09 08:46 UTC, alinadmytriv commented
Okey, thanks!

2023-04-27 07:59 UTC, closed without merging